# Generated by Django 4.2.4 on 2023-09-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_semester_end_date_alter_semester_start_date'),
        ('tuitionfee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee',
            name='idSemester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_tuitionfee', to='course.semester', verbose_name='Học kỳ'),
        ),
    ]
