# Generated by Django 4.2.4 on 2023-09-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_module_final_ratio_alter_module_process_ratio'),
        ('tuitionfee', '0002_alter_tuitionfee_idsemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuitionfee_scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField(verbose_name='Tiền một tín')),
                ('idSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name': 'Giá tín chỉ',
                'verbose_name_plural': 'Giá tín chỉ',
            },
        ),
    ]
