# Generated by Django 4.2.4 on 2023-09-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_module_final_ratio_alter_module_process_ratio'),
        ('tuitionfee', '0003_tuitionfee_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee_scale',
            name='idSemester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester', unique=True, verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='tuitionfee_scale',
            name='scale',
            field=models.FloatField(verbose_name='Học phí tín chỉ'),
        ),
    ]
