# Generated by Django 4.2.4 on 2023-09-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_module_final_ratio_alter_module_process_ratio'),
        ('tuitionfee', '0005_alter_tuitionfee_scale_idsemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee_scale',
            name='idSemester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Học kỳ'),
        ),
    ]
