# Generated by Django 4.2.4 on 2023-08-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('login_std', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idModule', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã học phần')),
                ('nameModule', models.CharField(max_length=70, verbose_name='Tên học phần')),
                ('credits', models.IntegerField(default=0, verbose_name='Số tín chỉ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Module_of_Department', to='faculty.department', verbose_name='Chuyên ngành')),
            ],
            options={
                'verbose_name': 'Học phần',
                'verbose_name_plural': 'Danh sách học phần',
            },
        ),
        migrations.CreateModel(
            name='ModuleClass',
            fields=[
                ('idModuleClass', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã lớp học phần')),
                ('idClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Module_of_idClass', to='faculty.facultyclasses', verbose_name='Lớp học phần')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module', verbose_name='Tên học phần')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Lớp học phần',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('idSemester', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã học kỳ')),
                ('nameSemester', models.CharField(max_length=30, verbose_name='Học kỳ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
            },
        ),
        migrations.CreateModel(
            name='Student_Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_grade', models.FloatField(default=0, verbose_name='Điểm quá trình')),
                ('final_grade', models.FloatField(default=0, verbose_name='Điểm kết thúc')),
                ('overall_grade', models.FloatField(default=0, verbose_name='Điểm tổng kết')),
                ('overall_grade_4', models.FloatField(default=0, verbose_name='Hệ số 4')),
                ('overall_grade_text', models.CharField(blank=True, max_length=2, verbose_name='Điểm chữ')),
                ('is_pass', models.BooleanField(choices=[(True, 'Đạt'), (False, 'Chưa đạt')], default=False, verbose_name='Đạt')),
                ('idStd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_module', to='login_std.profile_std', verbose_name='MSSV')),
                ('module_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_std', to='course.moduleclass', verbose_name='Học phần')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name': 'Bảng điểm',
                'verbose_name_plural': 'Bảng điểm',
            },
        ),
    ]
