# Generated by Django 4.2.4 on 2023-08-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_module',
            name='semester',
        ),
        migrations.AddField(
            model_name='moduleclass',
            name='enddate_registration',
            field=models.DateField(default='2023-08-24', verbose_name='Hạn đăng ký'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleclass',
            name='is_registration',
            field=models.BooleanField(choices=[(True, 'Mở'), (False, 'Đóng')], default=True, verbose_name='Mở đăng ký'),
        ),
        migrations.AddField(
            model_name='moduleclass',
            name='max_slot',
            field=models.PositiveIntegerField(default=100, verbose_name='Sĩ số tối đa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleclass',
            name='semester',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Học kỳ'),
            preserve_default=False,
        ),
    ]
