# Generated by Django 4.2.4 on 2023-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_student_module_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleclass',
            name='enddate_registration',
        ),
        migrations.RemoveField(
            model_name='moduleclass',
            name='is_registration',
        ),
        migrations.AddField(
            model_name='semester',
            name='enddate_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn đăng ký'),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_registration',
            field=models.BooleanField(choices=[(True, 'Mở'), (False, 'Đóng')], default=True, verbose_name='Mở đăng ký'),
        ),
    ]
