# Generated by Django 4.2.4 on 2023-08-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_std', '0001_initial'),
        ('course', '0003_remove_moduleclass_enddate_registration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Module',
            new_name='Student_ModuleClass',
        ),
    ]
