# Generated by Django 4.2.4 on 2023-09-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_facultyclasses_department'),
        ('course', '0005_alter_moduleclass_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.idcourse', verbose_name='Khóa')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name': 'Lịch đăng ký học phần',
                'verbose_name_plural': 'Lịch đăng ký học phần',
            },
        ),
    ]
