# Generated by Django 4.2.4 on 2023-09-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_registrationschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='enddate_registration',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_registration',
        ),
    ]
