# Generated by Django 4.2.4 on 2023-09-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_student_moduleclass_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_moduleclass',
            name='is_pass',
            field=models.BooleanField(blank=True, choices=[(True, 'Đạt'), (False, 'Chưa đạt')], null=True, verbose_name='Đạt'),
        ),
    ]
