# Generated by Django 4.2.4 on 2023-09-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_semester_end_date_alter_semester_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='final_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số điểm kết thúc'),
        ),
        migrations.AddField(
            model_name='module',
            name='process_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Hệ số điểm quá trình'),
        ),
    ]
