# Generated by Django 4.2.4 on 2023-09-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_module_final_ratio_module_process_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='final_ratio',
            field=models.FloatField(blank=True, default=0.7, null=True, verbose_name='Hệ số điểm kết thúc'),
        ),
        migrations.AlterField(
            model_name='module',
            name='process_ratio',
            field=models.FloatField(blank=True, default=0.3, null=True, verbose_name='Hệ số điểm quá trình'),
        ),
    ]
