# Generated by Django 4.2.4 on 2023-08-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('idDepartment', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã ngành')),
                ('nameDepartment', models.CharField(max_length=50, verbose_name='Tên Ngành')),
            ],
            options={
                'verbose_name': 'Ngành đào tạo',
                'verbose_name_plural': 'Ngành đào tạo',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('idFaculty', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã khoa')),
                ('nameFaculty', models.CharField(max_length=50, verbose_name='Tên khoa')),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Khoa',
            },
        ),
        migrations.CreateModel(
            name='idCourse',
            fields=[
                ('idCourse', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Mã khóa')),
                ('nameCourse', models.CharField(max_length=20, verbose_name='Tên khóa')),
            ],
            options={
                'verbose_name': 'Khóa sinh viên',
                'verbose_name_plural': 'Khóa sinh viên',
            },
        ),
        migrations.CreateModel(
            name='FacultyClasses',
            fields=[
                ('idClass', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã lớp')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department', verbose_name='Tên Ngành')),
                ('idCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.idcourse', verbose_name='Khóa')),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Lớp',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty', verbose_name='Tên Khoa'),
        ),
    ]
