# Generated by Django 4.2.4 on 2023-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsfeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề thông báo')),
                ('pdf_file', models.BinaryField(blank=True, null=True, verbose_name='file_pdf')),
                ('post_date', models.DateField(auto_now=True, null=True, verbose_name='Ngày đăng')),
                ('is_hidden', models.BooleanField(blank=True, choices=[(True, 'Hiện'), (False, 'Ẩn')], default=True, null=True, verbose_name='Ẩn / hiện')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
            },
        ),
    ]
