# Generated by Django 4.2.4 on 2023-09-19 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='pdf_file',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='file_pdf'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Ngày đăng'),
        ),
    ]
