# Generated by Django 4.2.4 on 2023-09-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_newsfeed_pdf_file_alter_newsfeed_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='pdf_file',
            field=models.BinaryField(blank=True, null=True, verbose_name='file_pdf'),
        ),
    ]
