# Generated by Django 4.2.4 on 2023-08-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_std',
            fields=[
                ('idStd', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='MSSV')),
                ('password', models.CharField(max_length=128, verbose_name='Mật khẩu')),
                ('nameStd', models.CharField(max_length=32, verbose_name='Họ và tên')),
                ('datebirthStd', models.DateField(verbose_name='Ngày sinh')),
                ('genderStd', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=5, verbose_name='Giới tính')),
                ('identityStd', models.CharField(blank=True, max_length=15, null=True, verbose_name='CCCD/CMND')),
                ('ethnicityStd', models.CharField(default='Kinh', max_length=10, verbose_name='Dân tộc')),
                ('phoneStd', models.CharField(blank=True, max_length=12, null=True, verbose_name='Điện thoại')),
                ('emailStd', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('addressStd', models.CharField(max_length=50, verbose_name='Quê quán')),
                ('graduate', models.BooleanField(choices=[(True, 'Chưa tốt nghiêp'), (False, 'Đã tốt nghiệp')], default=True, verbose_name='Tình trạng tốt nghiệp')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idClass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.facultyclasses', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Thông tin sinh viên',
                'verbose_name_plural': 'Sinh viên',
            },
        ),
    ]
