# Generated by Django 4.2.4 on 2023-09-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
