# Generated by Django 4.2.4 on 2023-09-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_admin', '0002_profile_admin_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_admin',
            old_name='sexAdmin',
            new_name='genderAdmin',
        ),
        migrations.RemoveField(
            model_name='profile_admin',
            name='ethnicityAdmin',
        ),
    ]
